### ISSUE TITLE
Changing Placeholder Text?

### ISSUE THREAD

**Issue by haleyngonadi** [mukyasa/MMTextFieldEffects#2]
Can the placeholder text only be accessed in the class? 

I tried subclassing my UITextField and doing this:

`self.emailField.placeHolderLabel = @"Email Address";
`

But it doesn't work?

**Comment by haleyngonadi** [comment]
Spelling was wrong. Got it now!

**Comment by mukyasa** [comment]
Great to hear to solved , Sorry i couldn't replied on time
